# Generated by Django 4.0.6 on 2022-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='chart',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_style',
            field=models.CharField(default='DefaultStyle', max_length=25),
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(default='bar', max_length=5),
        ),
        migrations.AddField(
            model_name='chart',
            name='repo',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
