# Generated by Django 4.0.6 on 2022-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_remove_chart_chart_chart_chart_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='path',
            field=models.CharField(default='', max_length=150),
        ),
    ]
